window.contestOpsData = {
  product: 'ContestOps AI',
  version: '0.5.0',
  prod: 86,
  milestone: {
    title: 'RAISE application packet',
    percent: 90,
    target: '2026-06-10',
  },
  deadline: 'June 10 hard deadline',
  opportunity: 'RAISE the STAKES 2026',
  category: 'AI startup pitch',
  metrics: [
    { label: 'Rules', value: '9/9', tone: 'teal' },
    { label: 'Evidence', value: '8/10', tone: 'amber' },
    { label: 'Dealum', value: 'mapped', tone: 'teal' },
    { label: 'Traction', value: 'collect', tone: 'red' },
  ],
  runs: [
    { time: '2026-05-29', name: 'Official source snapshot', status: 'done' },
    { time: '2026-05-29', name: 'RAISE V profile manifest', status: 'done' },
    { time: '2026-05-29', name: 'Application packet', status: 'done' },
    { time: '2026-05-29', name: 'Dealum draft receipt', status: 'done' },
    { time: '2026-06-10', name: 'Authenticated final submit', status: 'next' },
  ],
  checklist: [
    { title: 'AI is core to the product', status: 'active', owner: 'product' },
    { title: 'Funding below EUR 10M', status: 'planned', owner: 'founder' },
    { title: 'Registered legal entity', status: 'planned', owner: 'founder' },
    { title: 'Two-person team proof', status: 'planned', owner: 'founder' },
    { title: 'Live MVP or strong demo', status: 'active', owner: 'demo' },
    { title: 'Early traction proof', status: 'planned', owner: 'traction' },
    { title: 'Paris finalist attendance', status: 'planned', owner: 'founder' },
    { title: 'Dealum payload mapped', status: 'active', owner: 'automation' },
  ],
  evidence: [
    { name: 'Source snapshot', state: 'active', path: 'evidence/source_snapshot.md' },
    { name: 'V manifest', state: 'active', path: 'evidence/public/manifest.json' },
    { name: 'Application packet', state: 'active', path: 'docs/APPLICATION_PACKET.md' },
    { name: 'Dealum payload', state: 'active', path: 'submission/dealum_payload.json' },
    { name: 'WAIBAv trace', state: 'active', path: 'automation/output' },
    { name: 'Traction ledger', state: 'planned', path: 'evidence/private/traction' },
  ],
  automations: [
    { name: 'Dealum draft prepare', type: 'WAIBAv', state: 'ready' },
    { name: 'Dealum live form', type: 'WAIBAv', state: 'scheduled' },
    { name: 'Form field map', type: 'YAML', state: 'ready' },
    { name: 'Final submit receipt', type: 'WAIBAv', state: 'scheduled' },
  ],
};
